const messages = document.querySelector('#messages'), form = document.querySelector('#chat-form');
const input = document.querySelector('#message'), file = document.querySelector('#search-image');
const orderDialog = document.querySelector('#order-dialog'); window.orderDialog = orderDialog;
function message(text, owner='bot') { const node=document.createElement('div'); node.className=`${owner}-message`; node.textContent=text; messages.append(node); messages.scrollTop=messages.scrollHeight; }
function imageMessage(file) { const node=document.createElement('div'); node.className='user-message image-message'; const image=document.createElement('img'); image.src=URL.createObjectURL(file); image.alt='Product image sent for search'; node.append(image); messages.append(node); messages.scrollTop=messages.scrollHeight; }
function productCard(product) { const node=document.createElement('article'); node.className='product'; node.innerHTML=`<img src="${product.image_path}" alt="${product.name}"><h3>${product.name}</h3><p>${product.description}</p><strong>$${product.price}</strong> · ${product.quantity} available<br><button>Buy</button>`; node.querySelector('button').onclick=()=>{document.querySelector('#product-id').value=product.id;document.querySelector('#order-product').textContent=product.name;orderDialog.showModal()}; messages.append(node); }
const slug = location.pathname.startsWith('/business/') ? location.pathname.split('/').pop() : '';
async function shop(){if(slug){const response=await fetch(`/api/businesses/${slug}`);if(response.ok){document.querySelector('#business-name').textContent=(await response.json()).name;return}}const response=await fetch('/api/businesses');const list=await response.json();if(list.length)document.querySelector('#business-name').textContent=list[0].name;}
shop();
form.addEventListener('submit', async e=>{e.preventDefault(); const text=input.value.trim(); const selectedImage=file.files[0]; if(!text&&!selectedImage)return; if(selectedImage)imageMessage(selectedImage); if(text)message(text,'user'); const body=new FormData();body.append('message',text);body.append('business_slug',slug);if(selectedImage)body.append('image',selectedImage); input.value='';file.value='';const response=await fetch('/api/chat',{method:'POST',body});const data=await response.json();message(data.reply||data.detail);(data.products||[]).forEach(productCard);});
document.querySelector('#order-form').addEventListener('submit',async e=>{e.preventDefault();const body=new FormData();body.append('product_id',document.querySelector('#product-id').value);body.append('name',document.querySelector('#buyer-name').value);body.append('phone',document.querySelector('#buyer-phone').value);body.append('address',document.querySelector('#buyer-address').value);const response=await fetch('/api/orders',{method:'POST',body});if(response.ok){orderDialog.close();message('Your order was sent to the seller. They will contact you soon.');}else alert('Could not send the order.');});
